// <auto-generated />
using System;
using Boats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueEconomy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221121082549_tablesCreations")]
    partial class tablesCreations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BoatPayments.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Paidby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<float>("ammountCredited")
                        .HasColumnType("real");

                    b.Property<float>("ammountdebited")
                        .HasColumnType("real");

                    b.HasKey("PaymentId");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Users.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fromWhere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("physicalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("auth.Models.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("LoginId");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("auth.Models.Roles", b =>
                {
                    b.Property<int>("RolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolesId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("boats.Models.BoatStock", b =>
                {
                    b.Property<int>("BoatStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("boatLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("boatPrice")
                        .HasColumnType("real");

                    b.Property<string>("lifeJacket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noAnchor")
                        .HasColumnType("int");

                    b.Property<int>("noOfRope")
                        .HasColumnType("int");

                    b.Property<string>("sneb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sneg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoatStockId");

                    b.ToTable("boatStock");
                });

            modelBuilder.Entity("fboats.Models.Fishboats", b =>
                {
                    b.Property<int>("FishBoatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BoatStockId")
                        .HasColumnType("int");

                    b.Property<string>("noOfTraps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FishBoatsId");

                    b.HasIndex("BoatStockId")
                        .IsUnique();

                    b.ToTable("fishBoats");
                });

            modelBuilder.Entity("fishers.Models.FisherMansGroup", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("attachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("crewName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("district")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("physicalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("fisherMansgroup");
                });

            modelBuilder.Entity("fishers.Models.GroupMembers", b =>
                {
                    b.Property<int>("GroupMembersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GroupMembersFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupMembersLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupMembersMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupMembersPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupMembersZMANumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupMembersId");

                    b.ToTable("fisherMansGroupMembers");
                });

            modelBuilder.Entity("loans.Models.LoanBoat", b =>
                {
                    b.Property<int>("LoanBoatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BoatCodeNumbergenerated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CreditCost")
                        .HasColumnType("real");

                    b.Property<string>("HiredBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanBoatId");

                    b.ToTable("loanBoats");
                });

            modelBuilder.Entity("fboats.Models.Fishboats", b =>
                {
                    b.HasOne("boats.Models.BoatStock", "BoatStock")
                        .WithOne("FishBoats")
                        .HasForeignKey("fboats.Models.Fishboats", "BoatStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoatStock");
                });

            modelBuilder.Entity("boats.Models.BoatStock", b =>
                {
                    b.Navigation("FishBoats");
                });
#pragma warning restore 612, 618
        }
    }
}
