// <auto-generated />
using Boats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlueEconomy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221121081323_boatAndMwaniRelations1")]
    partial class boatAndMwaniRelations1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("boats.Models.BoatStock", b =>
                {
                    b.Property<int>("BoatStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("boatLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("boatPrice")
                        .HasColumnType("real");

                    b.Property<string>("lifeJacket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("noAnchor")
                        .HasColumnType("int");

                    b.Property<int>("noOfRope")
                        .HasColumnType("int");

                    b.Property<string>("sneb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sneg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoatStockId");

                    b.ToTable("boatStock");
                });

            modelBuilder.Entity("fboats.Models.Fishboats", b =>
                {
                    b.Property<int>("FishBoatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BoatStockId")
                        .HasColumnType("int");

                    b.Property<string>("noOfTraps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FishBoatsId");

                    b.HasIndex("BoatStockId")
                        .IsUnique();

                    b.ToTable("fishBoats");
                });

            modelBuilder.Entity("fboats.Models.Fishboats", b =>
                {
                    b.HasOne("boats.Models.BoatStock", "BoatStock")
                        .WithOne("FishBoats")
                        .HasForeignKey("fboats.Models.Fishboats", "BoatStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoatStock");
                });

            modelBuilder.Entity("boats.Models.BoatStock", b =>
                {
                    b.Navigation("FishBoats");
                });
#pragma warning restore 612, 618
        }
    }
}
